name: Release rikaikun
on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: '-d skips prepare and publish steps'
        required: false
        default: ''
  push:
    branches:
      - 'main'
    paths:
      - 'extension/data/*'
      - '!extension/data/deinflect.dat'

jobs:
  release:
    name: Release rikaikun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
      - name: Install dependencies and build
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: npx semantic-release ${{ github.event.inputs.dryRun}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: extension_package
          path: rikaikun.zip
