name: No unresolved comments
on:
  pull_request_review_comment:
    types: [deleted]
  pull_request_review:
    types: [submitted, dismissed]
  pull_request:
    types: [opened, reopened]

jobs:
  readResolutionStatus:
    name: 'Ensure no unresolved comments'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_comment_resolution_status
        with:
          query: |
            query release($owner:String!,$repo:String!, $pullrequest:Int!) {
              repository(owner:$owner,name:$repo) {
                pullRequest(number: $pullrequest) {
                  reviewThreads(last: 50) {
                    nodes {
                      isResolved
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pullrequest: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run:
          "checkLength() { read length; echo \"::set-output name=length::$length\"; if [ $length -gt 0 ]; then echo ::error ::There are $length unresolved comments; exit 1; fi; }; \
          echo '${{ steps.get_comment_resolution_status.outputs.data }}' | \
          jq '.repository.pullRequest.reviewThreads.nodes | map(select(.isResolved | not)) | length' | \
          checkLength"
        name: 'Unresolved Comments Check'
        id: unresolved_comments_check
      - name: 'Save Details'
        if: always()
        run: |
          mkdir -p ./desc
          echo 'There are ${{ steps.unresolved_comments_check.outputs.length}} unresolved comments.' > ./desc/DESC
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: desc
          path: desc/
