name: Update PR status
on:
  workflow_run:
    workflows: ['No unresolved comments']
    types:
      - completed

jobs:
  updatePRStatus:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set PR Status'
        uses: Sibz/github-status-action@v1.1.5
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{github.event.workflow_run.name}}
          description:
            'Failed with status ${{github.event.workflow_run.conclusion}} if this is wrong then be sure to
            double check or rerun jobs or remove label. Iff'
          state: ${{github.event.workflow_run.conclusion}}
          sha: ${{github.event.workflow_run.pull_requests[0].head.sha}}
