name: Update Dictionaries
on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  update-dicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Update dictionaries
        run: |
          npm ci
          echo 'update_output<<EOF' >> $GITHUB_ENV
          npm run update-db >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.RIKAIKUN_BOT_PAT }}
          author: rikaikun[bot] <83656842+rikaikun-bot@users.noreply.github.com>
          push-to-fork: rikaikun-bot/rikaikun
          commit-message: |
            fix(dict): Update dictionaries to latest versions.

            ${{ env.update_output }}
          title: 'fix(dict): Update dictionaries to latest versions.'
          body: |
            ${{ env.update_output }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: rikaikun-bot/update-dicts
