name: Update PR status
on:
  workflow_run:
    workflows: ['No unresolved comments']
    types:
      - completed

jobs:
  updatePRStatus:
    runs-on: ubuntu-latest
    steps:
      - run: "echo '${{github.event.workflow_run}}'"
        name: 'workflow_run ouput'
      - run: "echo '${{github.event.workflow}}'"
        name: 'workflow object output'

      - name: 'Set PR Status'
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{github.event.workflow_run.name}}
          description: 'Failed with status ${{github.event.workflow_run.conclusion}}'
          state: ${{github.event.workflow_run.conclusion}}
          sha: ${{github.event.workflow.pull_request.head.sha}}
