name: Update PR unresolved comment status
on:
  workflow_run:
    workflows: ['No unresolved comments']
    types:
      - completed

permissions:
  statuses: write

jobs:
  updatePRStatus:
    runs-on: ubuntu-latest
    steps:
      # TODO(melink14): Figure out how to print debug info safely.
      # - run: echo '::debug::${{ escapeData(toJson(github.event.workflow_run)) }}'
      #   name: 'workflow_run output'
      # - run: echo '::debug::${{ escapeData(toJson(github.event.workflow)) }}'
      #   name: 'workflow object output'
      # Adapted from https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
      - name: 'Download artifact'
        uses: actions/github-script@v4.0.2
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "desc"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{ github.workspace }}/desc.zip', Buffer.from(download.data));
      - run: unzip desc.zip
      - name: 'Read length'
        uses: actions/github-script@v4.0.2
        id: read_length
        with:
          script: |
            var fs = require('fs');
            return String(fs.readFileSync('./DESC')).trim();
          result-encoding: string
      - name: 'Create description'
        uses: actions/github-script@v4.0.2
        id: create_description
        with:
          script: |
            return 'There are ${{ steps.read_length.outputs.result }} unresolved comments. Re-run if stale by clicking on "Details".'
          result-encoding: string
      - name: 'Create status'
        uses: actions/github-script@v4.0.2
        id: create_status
        with:
          script: |
            return ${{ steps.read_length.outputs.result }} == '0' ? 'success' : 'failure'
          result-encoding: string
      - name: 'Set PR Status'
        uses: Sibz/github-status-action@v1.1.5
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ github.event.workflow_run.name }}
          description: ${{ steps.create_description.outputs.result }}
          state: ${{ steps.create_status.outputs.result }}
          sha: ${{ github.event.workflow_run.head_sha }}
          target_url: ${{ github.event.workflow_run.html_url }}
